export { default as BarChart } from '/@/components/Charts/src/BarChart.vue'; // 柱状图-单列
export { default as BarMulti } from '/@/components/Charts/src/BarMulti.vue'; // 柱状图-多列
export { default as DirectChart } from '/@/components/Charts/src/DirectChart.vue'; // 堆叠条形图
export { default as HBarChart } from '/@/components/Charts/src/HBarChart.vue'; // 柱状图-横向
export { default as LineChart } from '/@/components/Charts/src/LineChart.vue'; // 折线图
export { default as PieChart } from '/@/components/Charts/src/PieChart.vue'; // 饼图
export { default as RadarChart } from '/@/components/Charts/src/RadarChart.vue'; // 雷达图
export { default as RingChart } from '/@/components/Charts/src/RingChart.vue'; // 环形图
export { default as TangPolarChart } from '/@/components/Charts/src/TangPolarChart.vue'; // 极坐标图
